version: "2"
services:
  web:
    image: kpfromer/movie-chooser
    ports:
      - "80:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/movie-chooser
    depends_on:
      - mongo
    restart: always
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
    restart: always
volumes:
  data-volume:
